<div id="h" class="container">
	<div id="h-content" class="full-centered">
		<div class="header-back header-back--home"></div>
		<div class="wrapper">
			<h1>Home</h1>
			<p>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Cum sociis natoque penatibus et magnis. Viverra mauris in aliquam sem fringilla ut. Nunc faucibus a pellentesque sit amet porttitor eget dolor. A lacus vestibulum sed arcu. Tellus cras adipiscing enim eu. Egestas erat imperdiet sed euismod nisi porta. Lobortis mattis aliquam faucibus purus in massa. Enim eu turpis egestas pretium aenean pharetra magna ac placerat. Lacinia quis vel eros donec ac odio tempor. Aliquet porttitor lacus luctus accumsan. Fermentum et sollicitudin ac orci. Egestas sed tempus urna et pharetra pharetra massa massa. Duis at consectetur lorem donec massa sapien faucibus et. Et tortor consequat id porta. Ultricies tristique nulla aliquet enim.</p>

			<p>Dignissim diam quis enim lobortis scelerisque fermentum dui faucibus in. Elit sed vulputate mi sit. Augue interdum velit euismod in pellentesque massa. Nibh sed pulvinar proin gravida. Auctor augue mauris augue neque gravida. Nec feugiat nisl pretium fusce id velit ut tortor. Erat velit scelerisque in dictum non consectetur. Diam vel quam elementum pulvinar etiam non quam lacus suspendisse. Amet aliquam id diam maecenas ultricies mi eget. Quis blandit turpis cursus in hac habitasse. Ultricies mi eget mauris pharetra et. Commodo viverra maecenas accumsan lacus vel. Consectetur libero id faucibus nisl tincidunt. Sed turpis tincidunt id aliquet risus.</p>

			<p>Aliquet porttitor lacus luctus accumsan tortor posuere. Egestas integer eget aliquet nibh. Ultricies integer quis auctor elit sed vulputate mi sit. Vitae ultricies leo integer malesuada. Sociis natoque penatibus et magnis dis parturient montes nascetur ridiculus. Odio eu feugiat pretium nibh ipsum consequat. Curabitur gravida arcu ac tortor dignissim convallis. Eleifend quam adipiscing vitae proin sagittis nisl. Suspendisse ultrices gravida dictum fusce ut placerat orci. Dui nunc mattis enim ut tellus elementum. Pellentesque elit eget gravida cum sociis. Ligula ullamcorper malesuada proin libero nunc consequat interdum varius. Nullam non nisi est sit amet facilisis magna. Non consectetur a erat nam at lectus urna duis. In fermentum posuere urna nec tincidunt praesent semper feugiat. Faucibus et molestie ac feugiat sed lectus vestibulum. Amet porttitor eget dolor morbi. Arcu dictum varius duis at consectetur lorem donec massa.</p>

			<p>Dignissim suspendisse in est ante in nibh mauris cursus. Amet massa vitae tortor condimentum lacinia quis vel eros. Volutpat odio facilisis mauris sit amet. Feugiat nibh sed pulvinar proin gravida hendrerit lectus. Dignissim diam quis enim lobortis scelerisque fermentum dui. Quis eleifend quam adipiscing vitae proin. Vel fringilla est ullamcorper eget nulla. Neque convallis a cras semper auctor. Pretium viverra suspendisse potenti nullam ac tortor vitae purus. Est lorem ipsum dolor sit. Elit duis tristique sollicitudin nibh sit amet commodo. Orci eu lobortis elementum nibh tellus. Neque vitae tempus quam pellentesque nec nam aliquam sem. In pellentesque massa placerat duis ultricies lacus sed turpis tincidunt. Eget lorem dolor sed viverra ipsum nunc. Blandit libero volutpat sed cras ornare. In ante metus dictum at.</p>

			<p>Dignissim enim sit amet venenatis urna cursus eget. Id volutpat lacus laoreet non curabitur gravida. Porttitor rhoncus dolor purus non enim praesent elementum facilisis. Elementum sagittis vitae et leo duis ut. Aliquam malesuada bibendum arcu vitae elementum curabitur vitae nunc. Enim sit amet venenatis urna cursus eget nunc scelerisque viverra. Lacus sed turpis tincidunt id. Sagittis eu volutpat odio facilisis mauris sit amet massa. Tortor at risus viverra adipiscing. Non sodales neque sodales ut etiam sit. Justo eget magna fermentum iaculis eu non. Cursus sit amet dictum sit. Molestie nunc non blandit massa enim nec dui nunc mattis. Potenti nullam ac tortor vitae. Rhoncus mattis rhoncus urna neque. Mauris sit amet massa vitae tortor condimentum. Fringilla ut morbi tincidunt augue interdum. Facilisi etiam dignissim diam quis.</p>
			<?= $this->data->msg; ?>
		</div>
    </div>
</div>
